--------------------------------------------------------
--  Constraints for Table CUST_LAB_TEST_EXT_FIELDS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_LAB_TEST_EXT_FIELDS" ADD CONSTRAINT "CUST_LAB_TEST_EXT_FIELDS_PK" PRIMARY KEY ("CUST_ID", "TEST_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_LAB_TEST_EXT_FIELDS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_LAB_TEST_EXT_FIELDS" MODIFY ("TEST_SEQ" NOT NULL ENABLE);
