--------------------------------------------------------
--  Constraints for Table CUST_PENDING_ORDER_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_PENDING_ORDER_SETTINGS" ADD CONSTRAINT "CUST_PENDING_ORDER_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_PENDING_ORDER_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_PENDING_ORDER_SETTINGS" MODIFY ("CANCEL_PENDING_ORDER" NOT NULL ENABLE);
