--------------------------------------------------------
--  Constraints for Table CUST_ORDERBOOKING_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" ADD CONSTRAINT "CUST_ORDERBOOKING_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("SEND_SAMPLE_TO_FACTORY" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("PO_COMPULSORY" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("SHOW_PROD_DIVISION" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("SHOW_FACTORY_DETAILS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("REQUIRE_DROP_TESTING" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("ALLOW_POSTPONE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("NOTIFY_CLIENT" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("SHARE_PERFERRED_TESTS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("SHARE_CHECKLIST" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("TURN_OFF_AI_ACCESS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("ALLOW_CHANGE_AQL" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("CUST_AQL_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("CRITICAL_DEFECTS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("MAJOR_DEFECTS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("MINOR_DEFECTS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("MAX_MEA_DEFECTS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("CUST_SAMPLE_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" MODIFY ("MEA_SAMPLE_LEVEL" NOT NULL ENABLE);
