--------------------------------------------------------
--  Constraints for Table CUST_INV_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" ADD CONSTRAINT "CUST_INV_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("COMBINE_OFFLINE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("PAYMENT_POPUP" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("SEND_INVOICE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("INVOICE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("REINS_TO_SUPPLIER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("SUP_ACC_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("CNY_INVOICE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("INVOICE_CURRENCY" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("USD_TO_CNY" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("USD_TO_HKD" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("ONLINE_PAY_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INV_SETTINGS" MODIFY ("DIS_TAX_ID" NOT NULL ENABLE);
