--------------------------------------------------------
--  Constraints for Table CUST_DASHBOARD_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_DASHBOARD_SETTINGS" ADD CONSTRAINT "CUST_DASHBOARD_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_DASHBOARD_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_DASHBOARD_SETTINGS" MODIFY ("ACCESS_DASHBOARD" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_DASHBOARD_SETTINGS" MODIFY ("SHOW_DATA_BY" NOT NULL ENABLE);
