--------------------------------------------------------
--  Constraints for Table CUST_MASTER_ACC_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_MASTER_ACC_SETTINGS" ADD CONSTRAINT "CUST_MASTER_ACC_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_MASTER_ACC_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MASTER_ACC_SETTINGS" MODIFY ("IS_SUPER_MASTER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MASTER_ACC_SETTINGS" MODIFY ("IS_MASTER" NOT NULL ENABLE);
