--------------------------------------------------------
--  Constraints for Table CUST_MULTI_REFBKS_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" ADD CONSTRAINT "CUST_MULTI_REFBKS_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" MODIFY ("APPROVE_REF" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" MODIFY ("NB_OF_REPORT_PER_MD" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" MODIFY ("CLC_NB_OF_REPORTS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" MODIFY ("CLC_NB_OF_CONTAINER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" MODIFY ("PEO_CALCULATION" NOT NULL ENABLE);
