--------------------------------------------------------
--  Constraints for Table CUST_RPT_CERT_EXT_FIELDS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS" ADD CONSTRAINT "CUST_RPT_CERT_EXT_FIELDS_PK" PRIMARY KEY ("CUST_ID", "REJ_CATEGORY_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS" MODIFY ("REJ_CATEGORY_SEQ" NOT NULL ENABLE);
