--------------------------------------------------------
--  Constraints for Table CUST_OL_STORAGE_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_OL_STORAGE_SETTINGS" ADD CONSTRAINT "CUST_OL_STORAGE_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_OL_STORAGE_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_OL_STORAGE_SETTINGS" MODIFY ("AUTO_ARCHIVE_AFTER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_OL_STORAGE_SETTINGS" MODIFY ("REORDER_RANGE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_OL_STORAGE_SETTINGS" MODIFY ("REMOVE_CHECKLIST_AFTER" NOT NULL ENABLE);
