--------------------------------------------------------
--  Constraints for Table CUST_RPT_CERT_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" ADD CONSTRAINT "CUST_RPT_CERT_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("WITH_ATTACHMENT" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("ATTACHMENT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("REPORT_TEMPLATE" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("SEND_MAIL_TO_SUPPLIER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("SAME_DAY_REPORT" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("ALLOW_REPORT_APPROVER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("NB_OF_REPORT_APPROVER" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("SUB_REPORT_ACCESS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("SCREEN_SHOT_REQUIRED" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("CUST_MAIL_SUBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("CUST_REPORT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("AUTO_APPROVE_REPORT" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("NB_OF_REJ_CATEGORIES" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("AUTO_SEND_IC" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("DIS_IC_FIELDS" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("FROZEN_IC" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" MODIFY ("IC_TYPE" NOT NULL ENABLE);
