--------------------------------------------------------
--  Constraints for Table CUST_RPT_CERT_EXT_FIELDS_2
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS_2" ADD CONSTRAINT "CUST_RPT_CERT_EXT_FIELDS_2_PK" PRIMARY KEY ("CUST_ID", "APPROVER_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS_2" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS_2" MODIFY ("APPROVER_SEQ" NOT NULL ENABLE);
