--------------------------------------------------------
--  Constraints for Table CUST_KPI_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" ADD CONSTRAINT "CUST_KPI_SETTINGS_PK" PRIMARY KEY ("CUST_ID") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" MODIFY ("SEND_WEEKLY_KPI" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" MODIFY ("SEND_EXCEL_KPI" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" MODIFY ("SEND_DASHBOARD_KPI" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" MODIFY ("KPI_CATEGORIZED" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" MODIFY ("SUP_KPI_CATEGORIZED" NOT NULL ENABLE);
