--------------------------------------------------------
--  Constraints for Table CUST_ORD_BKS_EXT_FIELDS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_ORD_BKS_EXT_FIELDS" ADD CONSTRAINT "CUST_ORD_BKS_EXT_FIELDS_PK" PRIMARY KEY ("CUST_ID", "FAV_TEST_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_ORD_BKS_EXT_FIELDS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_ORD_BKS_EXT_FIELDS" MODIFY ("FAV_TEST_SEQ" NOT NULL ENABLE);
