--------------------------------------------------------
--  Constraints for Table CUST_PROD_FAMILY_EXT_FIELDS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS" ADD CONSTRAINT "CUST_PROD_FAMILY_EXT_FIELDS_PK" PRIMARY KEY ("CUST_ID", "PROD_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS" MODIFY ("PROD_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS" MODIFY ("BOOKING_TYPE" NOT NULL ENABLE);
