--------------------------------------------------------
--  Constraints for Table CUST_INSP_AUDIT_EXT_FIELDS
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_INSP_AUDIT_EXT_FIELDS" ADD CONSTRAINT "CUST_INSP_AUDIT_EXT_FIELDS_PK" PRIMARY KEY ("CUST_ID", "COUNTRY_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_INSP_AUDIT_EXT_FIELDS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INSP_AUDIT_EXT_FIELDS" MODIFY ("COUNTRY_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_INSP_AUDIT_EXT_FIELDS" MODIFY ("COUNTRY" NOT NULL ENABLE);
