--------------------------------------------------------
--  Constraints for Table CUST_PROD_FAMILY_EXT_FIELDS_2
--------------------------------------------------------

  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS_2" ADD CONSTRAINT "CUST_PROD_FAM_EXT_FIELDS_2_PK" PRIMARY KEY ("CUST_ID", "FAVO_PROD_SEQ") ENABLE;
 
  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS_2" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS_2" MODIFY ("FAVO_PROD_SEQ" NOT NULL ENABLE);
