-- // create CUST_RPT_CERT_REJ_REASONS
-- Migration SQL that makes the change goes here.
CREATE TABLE AIDATAUSER.CUST_RPT_CERT_REJ_REASONS
  (
    CUST_ID          VARCHAR2 (32 CHAR) NOT NULL ,
    REJ_CATEGORY_SEQ NUMBER (4) NOT NULL ,
    REJ_REASON_SEQ   NUMBER (4) NOT NULL ,
    REJ_REASON       VARCHAR2 (300) ,
    CREATE_TIME      TIMESTAMP ,
    UPDATE_TIME      TIMESTAMP
  ) ;
COMMENT ON TABLE AIDATAUSER.CUST_RPT_CERT_REJ_REASONS
IS
  'Report Settings Reject Reason' ;
CREATE UNIQUE INDEX AIDATAUSER.CUST_RPT_CERT_REJ_REASONS_IDX ON AIDATAUSER.CUST_RPT_CERT_REJ_REASONS
  (
    CUST_ID ASC , REJ_CATEGORY_SEQ ASC , REJ_REASON_SEQ ASC
  )
  LOGGING ;

ALTER TABLE AIDATAUSER.CUST_RPT_CERT_REJ_REASONS ADD CONSTRAINT CUST_RPT_CERT_REJ_REASONS_PK PRIMARY KEY ( CUST_ID , REJ_CATEGORY_SEQ , REJ_REASON_SEQ ) ;

ALTER TABLE AIDATAUSER.CUST_RPT_CERT_REJ_REASONS ADD CONSTRAINT CUST_RPT_CERT_REJ_REASONS_FK FOREIGN KEY ( CUST_ID, REJ_CATEGORY_SEQ ) REFERENCES AIDATAUSER.CUST_RPT_CERT_EXT_FIELDS ( CUST_ID, REJ_CATEGORY_SEQ ) NOT DEFERRABLE ;




-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE CUST_RPT_CERT_REJ_REASONS CASCADE CONSTRAINTS;
