-- // alter CUST_INV_SETTINGS
-- Migration SQL that makes the change goes here.

ALTER TABLE AIDATAUSER.CUST_INV_SETTINGS DROP COLUMN CNY_INVOICE CASCADE CONSTRAINT ;
ALTER TABLE AIDATAUSER.CUST_INV_SETTINGS DROP COLUMN USD_TO_CNY CASCADE CONSTRAINT  ;
ALTER TABLE AIDATAUSER.CUST_INV_SETTINGS DROP COLUMN USD_TO_HKD CASCADE CONSTRAINT  ;
-- //@UNDO
-- SQL to undo the change goes here.


