--------------------------------------------------------
--  DDL for Table CUST_SALES_COMMISSION
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_SALES_COMMISSION" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"COMMISSION" NUMBER(4,2), 
	"COMMISSION_DATE" DATE, 
	"COMMISSION_COMMENT" VARCHAR2(256), 
	"SALES_MANAGER" VARCHAR2(50), 
	"MANAGER_RATE" NUMBER(4,2), 
	"REGIONAL_MANAGER" VARCHAR2(50), 
	"REGIONAL_MANAGER_RATE" NUMBER(4,2), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_SALES_COMMISSION"  IS 'Sales Commission';
