--------------------------------------------------------
--  DDL for Table CUST_KPI_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_KPI_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"SEND_WEEKLY_KPI" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEND_EXCEL_KPI" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEND_DASHBOARD_KPI" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"WEEKLY_KPI_TO" VARCHAR2(255), 
	"WEEKLY_KPI_CONTACT" VARCHAR2(100), 
	"MONTHLY_KPI_TO" VARCHAR2(255), 
	"MONTHLY_KPI_CONTACT" VARCHAR2(60), 
	"INCLUDE_COST" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"INCLUDE_AQL_RATE" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"INCLUDE_CLAIM_RATE" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"INCLUDE_SAMPLE" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"DASH_KPI_PER_SUPPLIER" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"KPI_CATEGORIZED" VARCHAR2(20 CHAR), 
	"SUP_KPI_CATEGORIZED" VARCHAR2(20 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_KPI_SETTINGS"  IS 'KPIs Settings';
