--------------------------------------------------------
--  DDL for Table CUST_RPT_CERT_EXT_FIELDS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"REJ_CATEGORY_SEQ" NUMBER(4,0), 
	"REJ_CATEGORY" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_1" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_2" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_3" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_4" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_5" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_6" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_7" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_8" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_9" VARCHAR2(60 CHAR), 
	"CATEGORY_REASON_10" VARCHAR2(60 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_RPT_CERT_EXT_FIELDS"  IS 'Report Settings Reject Reason';
