--------------------------------------------------------
--  DDL for Table CUST_MULTI_REFBKS_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"APPROVE_REF" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"ASK_NB_OF_REF" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"NB_OF_REF_PER_PRODUCT" NUMBER(3,0), 
	"NB_OF_REF_PER_REPORT" NUMBER(2,0) DEFAULT 6, 
	"NB_OF_REF_PER_MD" NUMBER(2,0) DEFAULT 6, 
	"NB_OF_PCS_PER_REF" NUMBER(20,0) DEFAULT 1500, 
	"NB_OF_REPORT_PER_MD" NUMBER(1,0) DEFAULT 2, 
	"CLC_NB_OF_REPORTS" NUMBER(1,0) DEFAULT 3, 
	"CLC_NB_OF_CONTAINER" NUMBER(1,0) DEFAULT 2, 
	"PEO_CALCULATION" VARCHAR2(16 CHAR) DEFAULT 'Per MD', 
	"CONTAINER_RATE" NUMBER(5,2), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_MULTI_REFBKS_SETTINGS"  IS 'Multi-References Booking Settings';
