--------------------------------------------------------
--  DDL for Table CUST_ORDERBOOKING_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"CLC_PERCENTAGE" NUMBER(3,0) DEFAULT 100, 
	"PSI_PERCENTAGE" NUMBER(3,0) DEFAULT 80, 
	"DUPRO_PERCENTAGE" NUMBER(3,0) DEFAULT 20, 
	"IPC_PERCENTAGE" NUMBER(3,0) DEFAULT 10, 
	"PM_PERCENTAGE" NUMBER(3,0) DEFAULT 5, 
	"SEND_MODIFICATION_MAIL" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEND_SAMPLE_TO_FACTORY" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"PO_COMPULSORY" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SHOW_PROD_DIVISION" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"AVAILABLE_DIVISIONS" VARCHAR2(100 CHAR), 
	"SHOW_FACTORY_DETAILS" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"REQUIRE_DROP_TESTING" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"ALLOW_POSTPONE" VARCHAR2(3 CHAR), 
	"NOTIFY_CLIENT" VARCHAR2(3 CHAR), 
	"SHARE_PERFERRED_TESTS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SHARE_CHECKLIST" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"TURN_OFF_AI_ACCESS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"ALLOW_CHANGE_AQL" VARCHAR2(20 CHAR) DEFAULT 'Change allowed', 
	"CUST_AQL_LEVEL" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"CRITICAL_DEFECTS" VARCHAR2(16 CHAR) DEFAULT 'Not Allowed', 
	"MAJOR_DEFECTS" VARCHAR2(16 CHAR) DEFAULT '2.5', 
	"MINOR_DEFECTS" VARCHAR2(16 CHAR) DEFAULT '4', 
	"MAX_MEA_DEFECTS" VARCHAR2(16 CHAR) DEFAULT 'Not Allowed', 
	"CUST_SAMPLE_LEVEL" VARCHAR2(16 CHAR) DEFAULT 'II', 
	"MEA_SAMPLE_LEVEL" VARCHAR2(16) DEFAULT 'S4', 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_ORDERBOOKING_SETTINGS"  IS 'Order Booking Settings';
