--------------------------------------------------------
--  DDL for Table CUST_LEAD_QUAL
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_LEAD_QUAL" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"FIRST_ACC" VARCHAR2(3 CHAR), 
	"LEAD_TYPE" VARCHAR2(32 CHAR), 
	"QUALIFICATION" VARCHAR2(100 CHAR), 
	"POTENTIAL" VARCHAR2(100 CHAR), 
	"HAS_REFERRED" VARCHAR2(100 CHAR), 
	"SIC_COMMENTS" VARCHAR2(4000), 
	"FIRST_FEEDBACKS" VARCHAR2(2000 CHAR), 
	"REFERRER" VARCHAR2(128), 
	"KEY_CONTACT" VARCHAR2(512), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_LEAD_QUAL"  IS 'Lead Qualification';
