--------------------------------------------------------
--  DDL for Table CUST_RPT_CERT_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"CHB_REPORT_TO" VARCHAR2(8 CHAR) DEFAULT 'Sales', 
	"WITH_ATTACHMENT" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"ATTACHMENT_TYPE" VARCHAR2(5 CHAR) DEFAULT 'PDF', 
	"REPORT_CONTACT_NAME" VARCHAR2(60), 
	"REPORT_TEMPLATE" VARCHAR2(16 CHAR) DEFAULT 'Default', 
	"MAX_REPORT_SIZE" NUMBER(2,0) DEFAULT 5, 
	"RPT_APPROVER_NAME" VARCHAR2(100), 
	"SEND_MAIL_TO_SUPPLIER" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"SAME_DAY_REPORT" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"ALLOW_REPORT_APPROVER" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"NB_OF_REPORT_APPROVER" NUMBER(2,0) DEFAULT 0, 
	"SUB_REPORT_ACCESS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SCREEN_SHOT_REQUIRED" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"CUST_MAIL_SUBJECT" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"MAIL_SUBJECT_RULE" VARCHAR2(500), 
	"CUST_REPORT_NAME" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"REPORT_NAME_RULE" VARCHAR2(256), 
	"AUTO_APPROVE_REPORT" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"INCLUDE_APPROVAL_SHEET" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"NB_OF_REJ_CATEGORIES" NUMBER(2,0) DEFAULT 0, 
	"REJ_REASON_CATEGORY" VARCHAR2(16 CHAR) DEFAULT 'Defect Type', 
	"REJ_REASON_OTHER" VARCHAR2(200), 
	"AUTO_SEND_IC" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"DIS_IC_FIELDS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEND_IC_TO" VARCHAR2(16 CHAR) DEFAULT 'Supplier', 
	"SEND_IC_TO_SPECIFIED" VARCHAR2(256), 
	"COPY_IC_TO" VARCHAR2(16 CHAR) DEFAULT 'SIC'||' & '||'Client', 
	"COPY_IC_TO_SPECIFIED" VARCHAR2(256), 
	"BCC_IC_TO" VARCHAR2(16 CHAR) DEFAULT 'Supplier', 
	"FROZEN_IC" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"IC_TYPE" VARCHAR2(32 CHAR) DEFAULT 'Standard (DEFAULT)', 
	"IC_SIGNATURE" VARCHAR2(256), 
	"DAILY_REMINDER" VARCHAR2(256), 
	"WEEKLY_IC_REMINDER" VARCHAR2(256), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_RPT_CERT_SETTINGS"  IS 'Report Settings';
