--------------------------------------------------------
--  DDL for Table CUST_QUAL_MANUAL_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_QUAL_MANUAL_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"HAS_READ_QM" VARCHAR2(20 CHAR), 
	"QM_READ_TIME" TIMESTAMP (6), 
	"QM_FILE" BLOB, 
	"QM_RELEASE_DATE" DATE, 
	"QM_DUE_DATE" DATE, 
	"QM_REMINDER_REL" DATE, 
	"QM_REMINDER_DUE" DATE, 
	"QM_READ_HISTORY" VARCHAR2(4000), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_QUAL_MANUAL_SETTINGS"  IS 'Quality Manual Settings';
