--------------------------------------------------------
--  DDL for Table CUST_MARKETING_DATA
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_MARKETING_DATA" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"HEAR_FROM" VARCHAR2(50 CHAR), 
	"TRADE_SHOW_COUNTRY" VARCHAR2(64), 
	"TRADESHOW" VARCHAR2(64), 
	"RECOMMENDATION" VARCHAR2(30 CHAR), 
	"ADVERTISING" VARCHAR2(20 CHAR), 
	"HEAR_FROM_OTHER" VARCHAR2(256), 
	"NEWS_LETTER" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"SEARCH_ENGINE" VARCHAR2(500), 
	"SE_QUERY_USED" VARCHAR2(500), 
	"SEURL" VARCHAR2(500), 
	"REFERRED_ID" VARCHAR2(30 CHAR), 
	"REFERRED_BY" VARCHAR2(50 CHAR), 
	"REFERRED_DATE" DATE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_MARKETING_DATA"  IS 'Marketing Data';
