--------------------------------------------------------
--  DDL for Table CUST_MASTER_ACC_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_MASTER_ACC_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"IS_SUPER_MASTER" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"MASTER_LIST" VARCHAR2(2000), 
	"IS_MASTER" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SUB_COMPANY_LIST" VARCHAR2(2000), 
	"CAN_CREATE_ORDER" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"SHARE_FACTORY_LIB" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEE_PENDING_ORDERS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEE_ONLINE_REPORTS" VARCHAR2(3) DEFAULT 'Yes', 
	"SEE_ALL_FACTORIES" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"RECEIVE_ALL_MAILS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEND_ALL_MAILS_TO_SUB" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"ALL_MAILS_TO_SUB_CC_BCC" VARCHAR2(3 CHAR) DEFAULT 'Cc', 
	"SEND_REP_MAILS_TO_MASTER" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"SEND_REP_MAILS_TO_SUB" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"REP_MAILS_TO_SUB_CCBCC" VARCHAR2(3 CHAR) DEFAULT 'Cc', 
	"DIS_CLIENT_NAME" VARCHAR2(30 CHAR) DEFAULT 'Master Account', 
	"HIDE_APPROVE_BUTTON" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"HIDE_CC_FIELDS" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"ORDER_BILL_TO" VARCHAR2(60), 
	"REORDER_BILL_TO" VARCHAR2(60), 
	"LT_BILL_TO" VARCHAR2(60), 
	"AUDIT_BILL_TO" VARCHAR2(60), 
	"REAUDIT_BILL_TO" VARCHAR2(60), 
	"INVOICE_ISSUE_TYPE" VARCHAR2(100 CHAR), 
	"SUSPEND_ORDERS_BY" VARCHAR2(20 CHAR) DEFAULT 'By Company Name', 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_MASTER_ACC_SETTINGS"  IS 'Master Account Settings';
