--------------------------------------------------------
--  DDL for Table CUST_INV_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_INV_SETTINGS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"COMBINE_OFFLINE" VARCHAR2(3 CHAR) DEFAULT 'No', 
	"PAYMENT_POPUP" VARCHAR2(3 CHAR), 
	"SEND_INVOICE" VARCHAR2(20 CHAR) DEFAULT 'Automatic Invoicing', 
	"INVOICE_DATE" VARCHAR2(20 CHAR) DEFAULT 'End of the month', 
	"SPE_INV_DATE" NUMBER(2,0), 
	"REINS_TO_SUPPLIER" VARCHAR2(3 CHAR) DEFAULT 'Yes', 
	"SUP_ACC_NAME" VARCHAR2(60), 
	"SUP_ACC_GENDER" VARCHAR2(3 CHAR), 
	"SUP_ACC_TEL" VARCHAR2(30 CHAR), 
	"SUP_ACC_FAX" VARCHAR2(2000 CHAR), 
	"SUP_ACC_EMAIL" VARCHAR2(2000), 
	"SUP_ACC_COMMENT" VARCHAR2(2000), 
	"SUP_ACC_COM_NAME" VARCHAR2(256), 
	"CNY_INVOICE" VARCHAR2(4), 
	"INVOICE_CURRENCY" VARCHAR2(3 CHAR) DEFAULT 'USD', 
	"USD_TO_CNY" NUMBER(5,2) DEFAULT 6.4, 
	"USD_TO_HKD" NUMBER(5,2) DEFAULT 7.8, 
	"ONLINE_PAY_STATUS" VARCHAR2(32 CHAR) DEFAULT 'New Client v3', 
	"DIS_TAX_ID" VARCHAR2(4 CHAR) DEFAULT 'No', 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_INV_SETTINGS"  IS ' Invoicing Settings';
