--------------------------------------------------------
--  DDL for Table CUST_INSP_AUDIT_RATE
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_INSP_AUDIT_RATE" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"EXTRA_REPORT_RATE" NUMBER(8,0) DEFAULT 30, 
	"EXPRESS_FEE" NUMBER(8,0) DEFAULT 100, 
	"SAMPLE_FEE" NUMBER(8,0) DEFAULT 30, 
	"SP_RATE" NUMBER(8,0), 
	"GHP_RATE" NUMBER(8,0), 
	"GMP_RATE" NUMBER(8,0), 
	"CERTIFIED_AUDIT_RATE" NUMBER(8,0), 
	"NB_OF_COUNTRIES" NUMBER(4,0) DEFAULT 0, 
	"INSP_RATE_ASIA" NUMBER(8,0), 
	"INSP_RATE_AFRICA" NUMBER(8,0), 
	"INSP_RATE_EU" NUMBER(8,0), 
	"INSP_RATE_LATIN" NUMBER(8,0), 
	"AUDIT_RATE_ASIA" NUMBER(8,0), 
	"AUDIT_RATE_AFRICA" NUMBER(8,0), 
	"AUDIT_RATE_EU" NUMBER(8,0), 
	"AUDIT_RATE_LATIN" NUMBER(8,0), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_INSP_AUDIT_RATE"  IS 'Inspection & Audit Rates';
