--------------------------------------------------------
--  DDL for Table CUST_PROD_FAMILY_EXT_FIELDS
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS" 
   (	"CUST_ID" VARCHAR2(32 CHAR), 
	"PROD_SEQ" NUMBER(2,0), 
	"PROD_CATEGORY" VARCHAR2(64 CHAR), 
	"PROD_FAMILY" VARCHAR2(64 CHAR), 
	"PRODUCT_NAME" VARCHAR2(300 CHAR), 
	"MAX_PCS_PER_MD" NUMBER(8,0), 
	"BOOKING_TYPE" VARCHAR2(8 CHAR), 
	"MAX_POINTS_PER_MD" NUMBER(8,0), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
	"MAX_REF_PER_MD" NUMBER (8) NULL

   ) ;
 

   COMMENT ON TABLE "AIDATAUSER"."CUST_PROD_FAMILY_EXT_FIELDS"  IS 'Product Family Settings - Products';
