--------------------------------------------------------
--  DDL for Table UR_USER
--------------------------------------------------------

  CREATE TABLE "AIDATAUSER"."UR_USER" 
   (	"USER_ID" VARCHAR2(8 CHAR), 
	"FIRST_NAME" VARCHAR2(50 CHAR), 
	"LAST_NAME" VARCHAR2(50 CHAR), 
	"JOIN_DATE" DATE, 
	"DEPARTMENT_ID" VARCHAR2(4 CHAR), 
	"DEPARTMENT" VARCHAR2(50 CHAR), 
	"POSITION" VARCHAR2(50 CHAR), 
	"EMPLOYEE_TYPE" VARCHAR2(30 CHAR), 
	"EMAIL" VARCHAR2(255), 
	"PHONE" VARCHAR2(25 CHAR), 
	"LOGIN" VARCHAR2(128 CHAR), 
	"PASSWORD" VARCHAR2(128 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6)
   ) ;
